"""
从Moltemplate .lt文件生成匹配的PDB文件

功能：
    1. 解析.lt文件中的原子定义和坐标
    2. 生成与.lt文件原子数完全匹配的PDB文件
    3. 自动建立正确的CONECT记录（基于.lt中的键定义）

使用方法：
    python generate_pdb_from_lt.py

作者: 电解液MD平台
版本: 1.0.0
"""
import os
import re
from pathlib import Path


def parse_lt_file(lt_file_path):
    """
    解析Moltemplate .lt文件，提取原子定义和键定义

    Args:
        lt_file_path: .lt文件路径

    Returns:
        dict: 包含原子列表和键列表的字典
    """
    atoms = []
    bonds = []
    atom_id_counter = 0

    with open(lt_file_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            # 匹配原子定义: $atom:C1 $mol:. @atom:opls_209 +0.52 0.000 0.000 0.000
            if line.startswith('$atom:'):
                parts = line.split()
                if len(parts) >= 7:
                    atom_name = parts[0].split(':')[1]  # C1, O1, etc.
                    atom_type = parts[2].split(':')[-1]  # opls_209
                    charge = parts[3]  # +0.52
                    x = float(parts[4])
                    y = float(parts[5])
                    z = float(parts[6])
                    atom_id_counter += 1
                    # 从atom_type推断元素
                    element = infer_element(atom_name, atom_type)
                    atoms.append({
                        'id': atom_id_counter,
                        'name': atom_name,
                        'element': element,
                        'x': x, 'y': y, 'z': z
                    })
            # 匹配键定义: $bond:b_C1_O1 @bond:CO_double $atom:C1 $atom:O1
            elif line.startswith('$bond:'):
                parts = line.split()
                if len(parts) >= 4:
                    atom1_name = parts[2].split(':')[1]
                    atom2_name = parts[3].split(':')[1]
                    bonds.append((atom1_name, atom2_name))

    return {'atoms': atoms, 'bonds': bonds}


def infer_element(atom_name, atom_type):
    """
    从原子名或原子类型推断元素符号

    Args:
        atom_name: 原子名（如C1, O1, H1, Li, P1, F1）
        atom_type: 原子类型（如opls_209）

    Returns:
        str: 元素符号（C, O, H, Li, P, F等）
    """
    # 从原子名推断
    if atom_name.upper().startswith('LI'):
        return 'Li'
    elif atom_name.upper().startswith('PF6') or atom_name.upper().startswith('P'):
        return 'P'
    elif atom_name.upper().startswith('F'):
        return 'F'
    elif atom_name[0].upper() == 'C':
        return 'C'
    elif atom_name[0].upper() == 'O':
        return 'O'
    elif atom_name[0].upper() == 'H':
        return 'H'
    elif atom_name[0].upper() == 'N':
        return 'N'
    elif atom_name[0].upper() == 'S':
        return 'S'
    else:
        return atom_name[0].upper()


def generate_pdb(lt_data, molecule_name, output_path):
    """
    根据解析的.lt数据生成PDB文件

    Args:
        lt_data: parse_lt_file返回的字典
        molecule_name: 分子名称（如DMC, EC）
        output_path: 输出PDB文件路径
    """
    atoms = lt_data['atoms']
    bonds = lt_data['bonds']

    # 建立原子名到ID的映射
    atom_name_to_id = {atom['name']: atom['id'] for atom in atoms}

    lines = []
    lines.append(f"HEADER    {molecule_name}")
    lines.append(f"COMPND    {molecule_name}")
    lines.append("AUTHOR    GENERATED BY MD PLATFORM")

    # 写入原子坐标
    for atom in atoms:
        # PDB格式: ATOM  serial name resName resID x y z occupancy tempFactor element
        # 字段宽度: 6 5 1 4 1 3 1 1 4 1 3 8 8 8 6 6 12
        atom_serial = atom['id']
        atom_name_padded = atom['name'].ljust(3)
        element = atom['element']
        # 元素右对齐在最后两列
        element_padded = element.rjust(2)

        line = f"ATOM  {atom_serial:5d}  {atom_name_padded} {molecule_name}     1    {atom['x']:8.3f}{atom['y']:8.3f}{atom['z']:8.3f}  1.00  0.00          {element_padded}"
        lines.append(line)

    # 写入CONECT记录
    for atom1_name, atom2_name in bonds:
        if atom1_name in atom_name_to_id and atom2_name in atom_name_to_id:
            id1 = atom_name_to_id[atom1_name]
            id2 = atom_name_to_id[atom2_name]
            lines.append(f"CONECT {id1:4d} {id2:4d}")

    lines.append("END")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"生成PDB文件: {output_path} ({len(atoms)}个原子, {len(bonds)}个键)")


def main():
    """主函数：为所有分子模板生成匹配的PDB文件"""
    templates_dir = Path("/workspace/data/system_templates/molecule_templates")

    molecules = ['DMC', 'EC', 'LI', 'PF6']

    for mol_name in molecules:
        lt_file = templates_dir / mol_name / f"{mol_name}.lt"
        pdb_file = templates_dir / mol_name / f"{mol_name}.pdb"

        if not lt_file.exists():
            print(f"警告: {lt_file} 不存在，跳过")
            continue

        print(f"\n处理 {mol_name}:")
        print(f"  LT文件: {lt_file}")

        # 备份原PDB文件
        if pdb_file.exists():
            backup_file = pdb_file.with_suffix('.pdb.bak')
            pdb_file.rename(backup_file)
            print(f"  原PDB文件已备份: {backup_file}")

        # 解析LT文件
        lt_data = parse_lt_file(lt_file)
        print(f"  LT原子数: {len(lt_data['atoms'])}")
        print(f"  LT键数: {len(lt_data['bonds'])}")

        # 生成PDB文件
        generate_pdb(lt_data, mol_name, str(pdb_file))


if __name__ == '__main__':
    main()
