"""
修正DMC.pdb的3D坐标，使其符合真实分子几何结构

DMC（碳酸二甲酯）结构: O=C(OCH3)2
- C1: 中心羰基碳
- O1: 羰基氧（C=O双键）
- O2, O3: 醚氧（C-O单键）
- C2, C3: 甲基碳
- H1-H6: 甲基氢

作者: 电解液MD平台
版本: 1.0.0
"""
import math


def generate_dmc_pdb(output_path):
    """
    生成具有正确3D几何结构的DMC PDB文件

    使用标准分子几何参数:
    - C=O 键长: 1.20A
    - C-O 键长: 1.36A
    - O-CH3 键长: 1.43A
    - C-H 键长: 1.09A
    - O=C-O 角度: 120°
    - C-O-C 角度: 116°
    - H-C-H 角度: 109.5°（四面体）
    """
    # 原子定义: (name, element, x, y, z)
    # 以C1为原点，O1在+x方向，分子在xy平面
    c_o_double = 1.20  # C=O 双键
    c_o_single = 1.36  # C-O 单键
    o_c_methyl = 1.43  # O-CH3 键
    c_h = 1.09  # C-H 键

    # 角度（弧度）
    angle_oco = math.radians(120)  # O=C-O 角度
    angle_coc = math.radians(116)  # C-O-C 角度
    angle_hch = math.radians(109.5)  # H-C-H 四面体角度

    # C1 在原点
    c1 = (0.0, 0.0, 0.0)

    # O1 在+x方向（C=O双键）
    o1 = (c_o_double, 0.0, 0.0)

    # O2 和 O3 在C1的另一侧，夹角120°
    # O2 在120°方向
    o2_angle = math.pi - angle_oco / 2  # 从+x轴逆时针旋转
    o2 = (c_o_single * math.cos(o2_angle),
          c_o_single * math.sin(o2_angle),
          0.0)

    # O3 在-120°方向（对称）
    o3 = (c_o_single * math.cos(o2_angle),
          -c_o_single * math.sin(o2_angle),
          0.0)

    # C2 (甲基碳) 在O2的延长线上
    # O2-C2 方向与 C1-O2 方向成 angle_coc 角度
    o2_c1_angle = math.atan2(c1[1] - o2[1], c1[0] - o2[0])
    o2_c2_angle = o2_c1_angle - (math.pi - angle_coc)  # O-C-O角度
    c2 = (o2[0] + o_c_methyl * math.cos(o2_c2_angle),
          o2[1] + o_c_methyl * math.sin(o2_c2_angle),
          0.0)

    # C3 (甲基碳) 在O3的延长线上（对称）
    o3_c1_angle = math.atan2(c1[1] - o3[1], c1[0] - o3[0])
    o3_c3_angle = o3_c1_angle + (math.pi - angle_coc)
    c3 = (o3[0] + o_c_methyl * math.cos(o3_c3_angle),
          o3[1] + o_c_methyl * math.sin(o3_c3_angle),
          0.0)

    # H1, H2, H3 在C2上（四面体几何）
    # C2-H 方向与 O2-C2 方向相反，三个H呈四面体分布
    o2_c2_angle_h = math.atan2(c2[1] - o2[1], c2[0] - o2[0])
    # 三个H的角度：一个在分子平面内，两个在平面外
    h1_angle = o2_c2_angle_h + math.pi  # 反向
    h1 = (c2[0] + c_h * math.cos(h1_angle),
          c2[1] + c_h * math.sin(h1_angle),
          0.0)

    # H2 和 H3 在z方向偏移
    h2_angle = o2_c2_angle_h + math.pi - angle_hch / 2
    h2 = (c2[0] + c_h * math.cos(h2_angle) * math.cos(math.radians(30)),
          c2[1] + c_h * math.sin(h2_angle) * math.cos(math.radians(30)),
          c_h * math.sin(math.radians(30)))

    h3_angle = o2_c2_angle_h + math.pi + angle_hch / 2
    h3 = (c2[0] + c_h * math.cos(h3_angle) * math.cos(math.radians(30)),
          c2[1] + c_h * math.sin(h3_angle) * math.cos(math.radians(30)),
          -c_h * math.sin(math.radians(30)))

    # H4, H5, H6 在C3上（四面体几何，对称）
    o3_c3_angle_h = math.atan2(c3[1] - o3[1], c3[0] - o3[0])
    h4_angle = o3_c3_angle_h + math.pi
    h4 = (c3[0] + c_h * math.cos(h4_angle),
          c3[1] + c_h * math.sin(h4_angle),
          0.0)

    h5_angle = o3_c3_angle_h + math.pi - angle_hch / 2
    h5 = (c3[0] + c_h * math.cos(h5_angle) * math.cos(math.radians(30)),
          c3[1] + c_h * math.sin(h5_angle) * math.cos(math.radians(30)),
          c_h * math.sin(math.radians(30)))

    h6_angle = o3_c3_angle_h + math.pi + angle_hch / 2
    h6 = (c3[0] + c_h * math.cos(h6_angle) * math.cos(math.radians(30)),
          c3[1] + c_h * math.sin(h6_angle) * math.cos(math.radians(30)),
          -c_h * math.sin(math.radians(30)))

    # 原子列表（与DMC.lt顺序一致）
    atoms = [
        ('C1', 'C', c1), ('O1', 'O', o1), ('O2', 'O', o2), ('O3', 'O', o3),
        ('C2', 'C', c2), ('C3', 'C', c3),
        ('H1', 'H', h1), ('H2', 'H', h2), ('H3', 'H', h3),
        ('H4', 'H', h4), ('H5', 'H', h5), ('H6', 'H', h6),
    ]

    # 键定义（与DMC.lt一致）
    bonds = [
        (1, 2),  # C1-O1
        (1, 3),  # C1-O2
        (1, 4),  # C1-O3
        (3, 5),  # O2-C2
        (4, 6),  # O3-C3
        (5, 7), (5, 8), (5, 9),  # C2-H1,H2,H3
        (6, 10), (6, 11), (6, 12),  # C3-H4,H5,H6
    ]

    # 写入PDB文件
    lines = [
        "HEADER    DMC",
        "COMPND    DIMETHYL CARBONATE (DMC)",
        "AUTHOR    GENERATED BY MD PLATFORM",
    ]

    for i, (name, element, (x, y, z)) in enumerate(atoms, 1):
        lines.append(
            f"ATOM  {i:5d}  {name.ljust(3)} DMC     1    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {element.rjust(2)}"
        )

    for id1, id2 in bonds:
        lines.append(f"CONECT {id1:4d} {id2:4d}")

    lines.append("END")

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    # 验证原子间距离
    print(f"生成DMC.pdb: {len(atoms)}个原子")
    print("\n原子间距离验证:")
    for i in range(len(atoms)):
        for j in range(i + 1, len(atoms)):
            dx = atoms[i][2][0] - atoms[j][2][0]
            dy = atoms[i][2][1] - atoms[j][2][1]
            dz = atoms[i][2][2] - atoms[j][2][2]
            d = math.sqrt(dx * dx + dy * dy + dz * dz)
            if d < 1.0:  # 只显示距离<1.0A的原子对
                print(f"  {atoms[i][0]}-{atoms[j][0]}: {d:.3f}A")
            elif (i, j) in [(0, 1), (0, 2), (0, 3), (2, 4), (3, 5)]:  # 显示键长
                print(f"  {atoms[i][0]}-{atoms[j][0]}: {d:.3f}A (键)")


if __name__ == '__main__':
    generate_dmc_pdb('/workspace/data/system_templates/molecule_templates/DMC/DMC.pdb')
