"""
fix_molecule_pdb.py - 修复 DMC.pdb 和 EC.pdb 的 3D 坐标

功能：
    1. 生成 DMC（碳酸二甲酯）分子的正确 3D 几何构型
    2. 生成 EC（碳酸乙烯酯）分子的正确 3D 几何构型
    3. 确保所有原子间距离合理，避免 Packmol 初始构型重叠

分子几何参数（标准实验值）：
    键长：
        - C=O (羰基双键): 1.20 Å
        - C-O (酯键): 1.36 Å
        - O-CH3 (醚键): 1.43 Å
        - C-H: 1.09 Å
        - C-C (EC 环): 1.54 Å
    键角：
        - O=C-O (sp2): 120°
        - C-O-C (醚): 116°
        - O-C-H (sp3): 109.5°
        - H-C-H (sp3): 109.5°

作者: Electrolyte MD Platform
版本: 1.0
"""

import os
import math
import numpy as np


# ============================================================
# 向量运算工具函数
# ============================================================

def normalize(v):
    """归一化向量"""
    norm = np.linalg.norm(v)
    if norm < 1e-10:
        return v
    return v / norm


def rotate_vector(v, axis, angle_deg):
    """
    绕指定轴旋转向量
    使用 Rodrigues 旋转公式

    参数:
        v: 待旋转向量
        axis: 旋转轴（会自动归一化）
        angle_deg: 旋转角度（度）
    """
    axis = normalize(axis)
    angle = math.radians(angle_deg)
    cos_a = math.cos(angle)
    sin_a = math.sin(angle)
    # Rodrigues 旋转公式: v*cos + (k×v)*sin + k*(k·v)*(1-cos)
    return v * cos_a + np.cross(axis, v) * sin_a + axis * np.dot(axis, v) * (1 - cos_a)


def build_tetrahedral_hydrogens(center, bonded_atom, bond_length=1.09):
    """
    构建甲基（CH3）的三个氢原子，使用标准四面体几何

    参数:
        center: 甲基碳原子坐标 (numpy array)
        bonded_atom: 与甲基碳成键的原子坐标（用于确定方向）
        bond_length: C-H 键长

    返回:
        三个氢原子的坐标列表
    """
    # 主键方向（从 bonded_atom 指向 center）
    main_bond = normalize(center - bonded_atom)
    # 找一个与主键方向不平行的向量作为辅助轴
    if abs(main_bond[2]) < 0.9:
        helper = np.array([0.0, 0.0, 1.0])
    else:
        helper = np.array([1.0, 0.0, 0.0])
    # 构造垂直于主键的平面内的两个正交向量
    perp1 = normalize(np.cross(main_bond, helper))
    perp2 = normalize(np.cross(main_bond, perp1))

    # 四面体角: H-C-键 角度为 109.5°
    # main_bond 是从 bonded_atom 指向 center 的方向（即从 O 指向 C）
    # H 应该在 center 的另一侧（远离 bonded_atom），即沿 +main_bond 方向
    # H 方向与 main_bond 方向夹角为 180°-109.5° = 70.5°
    # 在垂直平面内三个 H 间隔 120°
    tilt_angle = 180.0 - 109.5  # 70.5°
    h_atoms = []
    for i in range(3):
        phi = 120.0 * i  # 0°, 120°, 240°
        # 在 perp1-perp2 平面内旋转，H 沿 +main_bond 方向（远离成键原子）
        direction = math.cos(math.radians(tilt_angle)) * main_bond + \
                    math.sin(math.radians(tilt_angle)) * \
                    (math.cos(math.radians(phi)) * perp1 + math.sin(math.radians(phi)) * perp2)
        direction = normalize(direction)
        h_pos = center + bond_length * direction
        h_atoms.append(h_pos)
    return h_atoms


# ============================================================
# PDB 文件写入
# ============================================================

def write_pdb(filename, header, atoms, bonds):
    """
    写入 PDB 文件

    参数:
        filename: 输出文件路径
        header: PDB 头信息
        atoms: 原子列表，每个元素为 (name, element, x, y, z)
        bonds: 键列表，每个元素为 (atom1_idx, atom2_idx)（1-based）
    """
    with open(filename, 'w') as f:
        f.write(f"HEADER    {header}\n")
        f.write(f"COMPND    {header}\n")
        f.write("AUTHOR    GENERATED BY MD PLATFORM\n")
        for i, (name, element, x, y, z) in enumerate(atoms, 1):
            # PDB 格式: ATOM  序号 原子名 残基名 残基序号 x y z 占据率 温度因子 元素
            f.write(f"ATOM  {i:5d}  {name:<3s} {header:<3s}     1    "
                    f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {element:>2s}\n")
        for b1, b2 in bonds:
            f.write(f"CONECT {b1:5d}{b2:5d}\n")
        f.write("END\n")
    print(f"已生成: {filename} ({len(atoms)} 个原子, {len(bonds)} 个键)")


# ============================================================
# DMC（碳酸二甲酯）分子生成
# ============================================================

def generate_dmc():
    """
    生成 DMC 分子的 3D 坐标

    分子结构:
        O1
        ||
        C1 — O2 — C2(H1,H2,H3)
         |
         O3 — C3(H4,H5,H6)

    几何参数:
        - C1=O1: 1.20 Å (沿 +z 方向)
        - C1-O2: 1.36 Å (在 xy 平面内)
        - C1-O3: 1.36 Å (在 xy 平面内)
        - O2-C2: 1.43 Å
        - O3-C3: 1.43 Å
        - O=C-O 角: 120°
        - C-O-C 角: 116°
    """
    # 键长
    r_CO_double = 1.20   # C=O 双键
    r_CO_single = 1.36   # C-O 单键
    r_OC = 1.43          # O-CH3 键
    r_CH = 1.09          # C-H 键

    # C1 在原点
    c1 = np.array([0.0, 0.0, 0.0])
    # O1 沿 +z 方向（C=O 双键）
    o1 = c1 + np.array([0.0, 0.0, r_CO_double])
    # O2 在 xy 平面，与 O1 夹角 120°（即与 +z 方向夹角 120°，在 xy 平面）
    # O2 = 1.36 * (sin(120°), 0, cos(120°)) = 1.36 * (0.866, 0, -0.5)
    o2 = c1 + r_CO_single * np.array([math.sin(math.radians(120)), 0.0, math.cos(math.radians(120))])
    # O3 在 xy 平面另一侧，与 O1 夹角 120°，与 O2 夹角 120°
    # O3 = 1.36 * (sin(120°)*cos(120°), sin(120°)*sin(120°), cos(120°))
    # 简化：O3 在 xy 平面内与 O2 关于 z 轴对称的另一侧
    o3 = c1 + r_CO_single * np.array([math.sin(math.radians(120)) * math.cos(math.radians(120)),
                                       math.sin(math.radians(120)) * math.sin(math.radians(120)),
                                       math.cos(math.radians(120))])
    # 实际上更简单：O2 在 xz 平面，O3 在 xz 平面另一侧（关于 z 轴对称）
    # 让我重新计算：C1 在原点，O1 沿 +z，O2 和 O3 在与 O1 夹角 120° 的方向上
    # O2 方向: (sin(120°), 0, cos(120°)) = (0.866, 0, -0.5)
    # O3 方向: (-sin(120°), 0, cos(120°)) 不对，这样 O2-O3 角度只有 60°
    # 正确: O2 和 O3 在与 O1 夹角 120° 的圆锥上，且 O2-O3 之间夹角也是 120°
    # 让 O2 在 xz 平面正侧: (sin(120°), 0, cos(120°))
    # O3 在 xz 平面负侧: (-sin(120°), 0, cos(120°)) — 这样 O2-O3 夹角是 2*arcsin(sin(120°)) = ?
    # 实际上，三个氧原子在以 C1 为中心、与 C1-O1 轴夹角 120° 的圆锥上，间隔 120°
    # O1 = (0, 0, 1.20)
    # O2 = 1.36 * (sin(120°)*cos(0), sin(120°)*sin(0), cos(120°)) = 1.36*(0.866, 0, -0.5)
    # O3 = 1.36 * (sin(120°)*cos(120°), sin(120°)*sin(120°), cos(120°)) = 1.36*(-0.433, 0.75, -0.5)
    # 验证 O2-O3 距离: sqrt((0.866+0.433)^2 + (0-0.75)^2 + 0) = sqrt(1.687 + 0.5625) = sqrt(2.25) = 1.5
    # 实际期望: O2-O3 = 2*1.36*sin(120°/2) = 2*1.36*sin(60°) = 2*1.36*0.866 = 2.356
    # 不对，O2-C1-O3 角度应该是 120°，O2-O3 = 2*1.36*sin(60°) = 2.356
    # 我的计算结果 1.5 不对，让我重新算
    # O2 = 1.36 * (0.866, 0, -0.5) = (1.178, 0, -0.68)
    # O3 = 1.36 * (-0.433, 0.75, -0.5) = (-0.589, 1.02, -0.68)
    # O2-O3 = (1.767, -1.02, 0), |O2-O3| = sqrt(3.122 + 1.04) = sqrt(4.162) = 2.04
    # 还是不对，应该是 2.356

    # 让我用更直接的方法：三个氧原子在 xy 平面内，间隔 120°，C1 在原点
    # O1 沿 +x 方向: (1.20, 0, 0)
    # O2 在 xy 平面，与 O1 夹角 120°: (1.36*cos(120°), 1.36*sin(120°), 0) = (-0.68, 1.177, 0)
    # O3 在 xy 平面，与 O1 夹角 240°（即 -120°）: (1.36*cos(240°), 1.36*sin(240°), 0) = (-0.68, -1.177, 0)
    # 这样 O2-O3 = 2*1.177 = 2.354，符合 2*1.36*sin(60°) = 2.356 ✓
    o1 = np.array([r_CO_double, 0.0, 0.0])
    o2 = np.array([r_CO_single * math.cos(math.radians(120)),
                   r_CO_single * math.sin(math.radians(120)),
                   0.0])
    o3 = np.array([r_CO_single * math.cos(math.radians(240)),
                   r_CO_single * math.sin(math.radians(240)),
                   0.0])

    # C2: 从 O2 延伸 O-CH3 键，C-O-C 角度 116°
    # C1-O2 方向: (o2 - c1) = o2，归一化
    c1_o2_dir = normalize(o2 - c1)
    # C2 在 O2 的延伸方向上，但与 C1-O2 方向夹角为 180°-116° = 64°（向外）
    # 让 C2 在 xy 平面外侧（远离 C1 方向）
    # O2 处的 C-O-C 角度: C1-O2-C2 = 116°，所以 O2-C2 方向与 O2-C1 方向夹角 116°
    # O2-C1 方向 = -c1_o2_dir
    # 让 C2 在 xy 平面内，O2-C2 方向 = 旋转 (-c1_o2_dir) 绕 z 轴旋转 (180°-116°)=64°
    # 即 O2-C2 方向与 O2-C1 方向（指向 C1）夹角 116°
    # 简化：C2 = O2 + 1.43 * (从 C1->O2 方向绕 z 轴旋转 -64°)
    # 这样 C2 在 O2 外侧，C1-O2-C2 角度为 180°-64°=116°
    o2_c2_dir = rotate_vector(c1_o2_dir, np.array([0, 0, 1]), -64.0)
    c2 = o2 + r_OC * o2_c2_dir

    # C3: 对称地，从 O3 延伸
    c1_o3_dir = normalize(o3 - c1)
    # O3 在下方，C3 应该在 O3 外侧（绕 z 轴旋转 +64°，因为 O3 在第三象限）
    o3_c3_dir = rotate_vector(c1_o3_dir, np.array([0, 0, 1]), 64.0)
    c3 = o3 + r_OC * o3_c3_dir

    # C2 的三个氢原子（四面体几何）
    h1, h2, h3 = build_tetrahedral_hydrogens(c2, o2, r_CH)
    # C3 的三个氢原子
    h4, h5, h6 = build_tetrahedral_hydrogens(c3, o3, r_CH)

    atoms = [
        ('C1', 'C', c1[0], c1[1], c1[2]),
        ('O1', 'O', o1[0], o1[1], o1[2]),
        ('O2', 'O', o2[0], o2[1], o2[2]),
        ('O3', 'O', o3[0], o3[1], o3[2]),
        ('C2', 'C', c2[0], c2[1], c2[2]),
        ('C3', 'C', c3[0], c3[1], c3[2]),
        ('H1', 'H', h1[0], h1[1], h1[2]),
        ('H2', 'H', h2[0], h2[1], h2[2]),
        ('H3', 'H', h3[0], h3[1], h3[2]),
        ('H4', 'H', h4[0], h4[1], h4[2]),
        ('H5', 'H', h5[0], h5[1], h5[2]),
        ('H6', 'H', h6[0], h6[1], h6[2]),
    ]

    bonds = [
        (1, 2),   # C1-O1
        (1, 3),   # C1-O2
        (1, 4),   # C1-O3
        (3, 5),   # O2-C2
        (4, 6),   # O3-C3
        (5, 7), (5, 8), (5, 9),     # C2-H1, C2-H2, C2-H3
        (6, 10), (6, 11), (6, 12),  # C3-H4, C3-H5, C3-H6
    ]

    return atoms, bonds


# ============================================================
# EC（碳酸乙烯酯）分子生成
# ============================================================

def generate_ec():
    """
    生成 EC 分子的 3D 坐标

    分子结构（五元环）:
        O1
        ||
        C1 — O2 — C2 — C3 — O3 — C1 (闭环)

    几何参数:
        - C1=O1: 1.20 Å (羰基双键)
        - C1-O2: 1.36 Å
        - C1-O3: 1.36 Å
        - O2-C2: 1.43 Å
        - O3-C3: 1.43 Å
        - C2-C3: 1.54 Å
        - C-H: 1.09 Å (4 个氢，每个 CH2 两个)

    五元环角度: 内角约 108°（接近正五边形）
    """
    # 键长
    r_CO_double = 1.20   # C=O 双键
    r_CO_single = 1.36   # C-O 单键
    r_OC = 1.43          # O-CH2 键
    r_CC = 1.54          # C-C 键
    r_CH = 1.09          # C-H 键

    # 构建五元环 C1-O2-C2-C3-O3-C1
    # 让五元环在 xy 平面，C1 在底部，O1 沿 -y 方向（向下）
    # 五元环顶点（正五边形，中心在原点，半径 r）
    # 内角 108°，但 EC 五元环不是正五边形，简化为近似正五边形
    # 五元环半径: 由键长决定
    # 正五边形边长 a 与外接圆半径 R 的关系: a = 2*R*sin(36°), R = a/(2*sin(36°))
    # 平均键长 ≈ (1.36+1.43+1.54+1.43+1.36)/5 = 1.424
    avg_bond = 1.424
    R = avg_bond / (2 * math.sin(math.radians(36)))

    # 五元环顶点（C1, O2, C2, C3, O3）按逆时针排列
    # 让 C1 在底部（角度 -90°，即 -y 方向）
    # 顶点角度: -90°, -90°+72°=-18°, -90°+144°=54°, -90°+216°=126°, -90°+288°=198°
    angles = [-90 + 72 * i for i in range(5)]
    ring_atoms = [np.array([R * math.cos(math.radians(a)),
                            R * math.sin(math.radians(a)),
                            0.0]) for a in angles]

    # 按顺序: C1, O2, C2, C3, O3
    c1, o2, c2, c3, o3 = ring_atoms

    # O1: C=O 双键，从 C1 向外（远离环中心）方向
    # C1 在 -y 方向，所以 O1 沿 -y 方向延伸
    c1_to_center = normalize(np.array([0, 0, 0]) - c1)  # 从 C1 指向环中心
    o1 = c1 + r_CO_double * (-c1_to_center)  # O1 沿 C1 远离中心方向

    # 调整环内键长（正五边形边长可能不等于实际键长）
    # 简化：保持正五边形几何，键长近似即可（Packmol 只需要初始构型）

    # C2 的两个氢原子（CH2，sp3 杂化）
    # C2 连接 O2 和 C3，H 在环平面外
    # C2-H 方向: 垂直于 O2-C2-C3 平面，向 +z 和 -z 方向
    c2_normal = np.array([0, 0, 1.0])  # 环平面法向
    # C2-H 方向在环平面外侧 + 法向方向
    # 简化：两个 H 对称分布在环平面上下
    # C2 中心方向（远离环中心）
    c2_outward = normalize(c2 - np.array([0, 0, 0]))
    # H 方向 = outward 倾斜 + 法向
    tilt = math.cos(math.radians(60))  # 60° 倾斜
    h_dir1 = normalize(c2_outward * tilt + c2_normal * math.sin(math.radians(60)))
    h_dir2 = normalize(c2_outward * tilt - c2_normal * math.sin(math.radians(60)))
    h1 = c2 + r_CH * h_dir1
    h2 = c2 + r_CH * h_dir2

    # C3 的两个氢原子（对称）
    c3_outward = normalize(c3 - np.array([0, 0, 0]))
    h_dir3 = normalize(c3_outward * tilt + c2_normal * math.sin(math.radians(60)))
    h_dir4 = normalize(c3_outward * tilt - c2_normal * math.sin(math.radians(60)))
    h3 = c3 + r_CH * h_dir3
    h4 = c3 + r_CH * h_dir4

    atoms = [
        ('C1', 'C', c1[0], c1[1], c1[2]),
        ('O1', 'O', o1[0], o1[1], o1[2]),
        ('O2', 'O', o2[0], o2[1], o2[2]),
        ('O3', 'O', o3[0], o3[1], o3[2]),
        ('C2', 'C', c2[0], c2[1], c2[2]),
        ('C3', 'C', c3[0], c3[1], c3[2]),
        ('H1', 'H', h1[0], h1[1], h1[2]),
        ('H2', 'H', h2[0], h2[1], h2[2]),
        ('H3', 'H', h3[0], h3[1], h3[2]),
        ('H4', 'H', h4[0], h4[1], h4[2]),
    ]

    bonds = [
        (1, 2),   # C1-O1
        (1, 3),   # C1-O2
        (1, 4),   # C1-O3
        (3, 5),   # O2-C2
        (4, 6),   # O3-C3
        (5, 6),   # C2-C3
        (5, 7), (5, 8),   # C2-H1, C2-H2
        (6, 9), (6, 10),  # C3-H3, C3-H4
    ]

    return atoms, bonds


# ============================================================
# 验证原子距离
# ============================================================

def check_min_distance(atoms, name):
    """检查原子间最小距离，确保没有重叠"""
    min_dist = float('inf')
    min_pair = None
    coords = np.array([[a[2], a[3], a[4]] for a in atoms])
    for i in range(len(coords)):
        for j in range(i + 1, len(coords)):
            d = np.linalg.norm(coords[i] - coords[j])
            if d < min_dist:
                min_dist = d
                min_pair = (atoms[i][0], atoms[j][0])
    print(f"  {name}: 最小原子间距 = {min_dist:.3f} Å ({min_pair[0]}-{min_pair[1]})")
    if min_dist < 1.0:
        print(f"  警告: {name} 存在过近的原子对（< 1.0 Å）")
    else:
        print(f"  ✓ {name} 原子间距合理")
    return min_dist


# ============================================================
# 主函数
# ============================================================

def main():
    """主函数：生成 DMC 和 EC 的 PDB 文件"""
    # 基础路径
    base = r"d:\electrolyte-md-platform\data\md_platform_data\system_templates\molecule_templates"

    # 生成 DMC
    print("=" * 60)
    print("生成 DMC (碳酸二甲酯) PDB 文件")
    print("=" * 60)
    dmc_atoms, dmc_bonds = generate_dmc()
    check_min_distance(dmc_atoms, "DMC")
    dmc_path = os.path.join(base, "DMC", "DMC.pdb")
    # 备份原文件
    if os.path.exists(dmc_path):
        backup = dmc_path + ".bak2"
        if not os.path.exists(backup):
            os.rename(dmc_path, backup)
            print(f"  已备份原文件到 {backup}")
    write_pdb(dmc_path, "DMC", dmc_atoms, dmc_bonds)

    # 生成 EC
    print("\n" + "=" * 60)
    print("生成 EC (碳酸乙烯酯) PDB 文件")
    print("=" * 60)
    ec_atoms, ec_bonds = generate_ec()
    check_min_distance(ec_atoms, "EC")
    ec_path = os.path.join(base, "EC", "EC.pdb")
    # 备份原文件
    if os.path.exists(ec_path):
        backup = ec_path + ".bak2"
        if not os.path.exists(backup):
            os.rename(ec_path, backup)
            print(f"  已备份原文件到 {backup}")
    write_pdb(ec_path, "EC", ec_atoms, ec_bonds)

    print("\n" + "=" * 60)
    print("所有 PDB 文件生成完成")
    print("=" * 60)


if __name__ == "__main__":
    main()
